{{- if .Values.vaultCRD.admissionWebhook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-crd-tls
data:
  tls.crt: {{ .Values.vaultCRD.admissionWebhook.certBase64 }}
  tls.key: {{ .Values.vaultCRD.admissionWebhook.keyBase64 }}
{{ end }}