apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault-crd.fullname" . }}-logback
  namespace: {{ .Release.Namespace }}
data:
  logback-spring.xml: |
    <configuration debug="true" scan="true">

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>{"date": "%date", "level": "%level", "logger": "%logger", "message": "%replace(%replace(%replace(%message){'\n', '\\n'}){'\t', '\\t'}){'"', '\"'}", "exception": "%replace(%replace(%replace(%xException){'\n', '\\n'}){'\t', '\\t'}){'"', '\"'}" } %n</pattern>
            </encoder>
        </appender>



        <!-- use this to setup global logging level with one command -->
        <root level="INFO">
                <!--<appender-ref ref="ASYNC"/>-->
        <appender-ref ref="STDOUT"/>
        </root>

    </configuration>