{{- if eq .Values.vaultCRD.vaultAuth "token" }}
apiVersion: v1
kind: Secret
metadata:
    name: "{{ include "vault-crd.fullname" . }}-vault-token"
data:
    token: "{{required "vaultCRD.vaultToken token must be specified" .Values.vaultCRD.vaultToken | b64enc}}"
{{ end }}
